export const GET_USERLIST = 'GET_USERLIST';
export const MERGE_USERLIST = 'MERGE_USERLIST';
export const POST_USERLIST = 'POST_USERLIST';
export const ADD_USERLIST = 'ADD_USERLIST';
export const DELETE_USERLIST = 'DELETE_USERLIST';
export const REMOVE_USERLIST = 'REMOVE_USERLIST';
export const PUT_USERLIST = 'PUT_USERLIST';
export const UPDATE_USERLIST = 'UPDATE_USERLIST';